// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/go.grpc.srv.cm.proto

package proto

import (
	"context"
	"fmt"
	"github.com/golang/protobuf/proto"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrpcGetIdsRequest struct {
	Nums                 int64    `protobuf:"varint,1,opt,name=Nums,proto3" json:"Nums,omitempty"`
	DataCenterId         int64    `protobuf:"varint,2,opt,name=DataCenterId,proto3" json:"DataCenterId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcGetIdsRequest) Reset()         { *m = GrpcGetIdsRequest{} }
func (m *GrpcGetIdsRequest) String() string { return proto.CompactTextString(m) }
func (*GrpcGetIdsRequest) ProtoMessage()    {}
func (*GrpcGetIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_168abdf897692c92, []int{0}
}

func (m *GrpcGetIdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcGetIdsRequest.Unmarshal(m, b)
}
func (m *GrpcGetIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcGetIdsRequest.Marshal(b, m, deterministic)
}
func (m *GrpcGetIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcGetIdsRequest.Merge(m, src)
}
func (m *GrpcGetIdsRequest) XXX_Size() int {
	return xxx_messageInfo_GrpcGetIdsRequest.Size(m)
}
func (m *GrpcGetIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcGetIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcGetIdsRequest proto.InternalMessageInfo

func (m *GrpcGetIdsRequest) GetNums() int64 {
	if m != nil {
		return m.Nums
	}
	return 0
}

func (m *GrpcGetIdsRequest) GetDataCenterId() int64 {
	if m != nil {
		return m.DataCenterId
	}
	return 0
}

type GrpcGetIdsResponse struct {
	Id                   []int64  `protobuf:"varint,1,rep,packed,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcGetIdsResponse) Reset()         { *m = GrpcGetIdsResponse{} }
func (m *GrpcGetIdsResponse) String() string { return proto.CompactTextString(m) }
func (*GrpcGetIdsResponse) ProtoMessage()    {}
func (*GrpcGetIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_168abdf897692c92, []int{1}
}

func (m *GrpcGetIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcGetIdsResponse.Unmarshal(m, b)
}
func (m *GrpcGetIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcGetIdsResponse.Marshal(b, m, deterministic)
}
func (m *GrpcGetIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcGetIdsResponse.Merge(m, src)
}
func (m *GrpcGetIdsResponse) XXX_Size() int {
	return xxx_messageInfo_GrpcGetIdsResponse.Size(m)
}
func (m *GrpcGetIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcGetIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcGetIdsResponse proto.InternalMessageInfo

func (m *GrpcGetIdsResponse) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

type GrpcGetIdRequest struct {
	DataCenterId         int64    `protobuf:"varint,1,opt,name=DataCenterId,proto3" json:"DataCenterId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcGetIdRequest) Reset()         { *m = GrpcGetIdRequest{} }
func (m *GrpcGetIdRequest) String() string { return proto.CompactTextString(m) }
func (*GrpcGetIdRequest) ProtoMessage()    {}
func (*GrpcGetIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_168abdf897692c92, []int{2}
}

func (m *GrpcGetIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcGetIdRequest.Unmarshal(m, b)
}
func (m *GrpcGetIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcGetIdRequest.Marshal(b, m, deterministic)
}
func (m *GrpcGetIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcGetIdRequest.Merge(m, src)
}
func (m *GrpcGetIdRequest) XXX_Size() int {
	return xxx_messageInfo_GrpcGetIdRequest.Size(m)
}
func (m *GrpcGetIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcGetIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcGetIdRequest proto.InternalMessageInfo

func (m *GrpcGetIdRequest) GetDataCenterId() int64 {
	if m != nil {
		return m.DataCenterId
	}
	return 0
}

type GrpcGetIdResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcGetIdResponse) Reset()         { *m = GrpcGetIdResponse{} }
func (m *GrpcGetIdResponse) String() string { return proto.CompactTextString(m) }
func (*GrpcGetIdResponse) ProtoMessage()    {}
func (*GrpcGetIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_168abdf897692c92, []int{3}
}

func (m *GrpcGetIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcGetIdResponse.Unmarshal(m, b)
}
func (m *GrpcGetIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcGetIdResponse.Marshal(b, m, deterministic)
}
func (m *GrpcGetIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcGetIdResponse.Merge(m, src)
}
func (m *GrpcGetIdResponse) XXX_Size() int {
	return xxx_messageInfo_GrpcGetIdResponse.Size(m)
}
func (m *GrpcGetIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcGetIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcGetIdResponse proto.InternalMessageInfo

func (m *GrpcGetIdResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GrpcHealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcHealthRequest) Reset()         { *m = GrpcHealthRequest{} }
func (m *GrpcHealthRequest) String() string { return proto.CompactTextString(m) }
func (*GrpcHealthRequest) ProtoMessage()    {}
func (*GrpcHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_168abdf897692c92, []int{4}
}

func (m *GrpcHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcHealthRequest.Unmarshal(m, b)
}
func (m *GrpcHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcHealthRequest.Marshal(b, m, deterministic)
}
func (m *GrpcHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcHealthRequest.Merge(m, src)
}
func (m *GrpcHealthRequest) XXX_Size() int {
	return xxx_messageInfo_GrpcHealthRequest.Size(m)
}
func (m *GrpcHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcHealthRequest proto.InternalMessageInfo

type GrpcHealthResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcHealthResponse) Reset()         { *m = GrpcHealthResponse{} }
func (m *GrpcHealthResponse) String() string { return proto.CompactTextString(m) }
func (*GrpcHealthResponse) ProtoMessage()    {}
func (*GrpcHealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_168abdf897692c92, []int{5}
}

func (m *GrpcHealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcHealthResponse.Unmarshal(m, b)
}
func (m *GrpcHealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcHealthResponse.Marshal(b, m, deterministic)
}
func (m *GrpcHealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcHealthResponse.Merge(m, src)
}
func (m *GrpcHealthResponse) XXX_Size() int {
	return xxx_messageInfo_GrpcHealthResponse.Size(m)
}
func (m *GrpcHealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcHealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcHealthResponse proto.InternalMessageInfo

func (m *GrpcHealthResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GrpcHealthResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*GrpcGetIdsRequest)(nil), "proto.GrpcGetIdsRequest")
	proto.RegisterType((*GrpcGetIdsResponse)(nil), "proto.GrpcGetIdsResponse")
	proto.RegisterType((*GrpcGetIdRequest)(nil), "proto.GrpcGetIdRequest")
	proto.RegisterType((*GrpcGetIdResponse)(nil), "proto.GrpcGetIdResponse")
	proto.RegisterType((*GrpcHealthRequest)(nil), "proto.GrpcHealthRequest")
	proto.RegisterType((*GrpcHealthResponse)(nil), "proto.GrpcHealthResponse")
}

func init() { proto.RegisterFile("proto/go.grpc.srv.cm.proto", fileDescriptor_168abdf897692c92) }

var fileDescriptor_168abdf897692c92 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xbb, 0x49, 0x5b, 0xe9, 0x20, 0x5a, 0xc7, 0x83, 0x31, 0xa7, 0xb2, 0x7a, 0xe8, 0x69,
	0x0b, 0x0a, 0x1e, 0x44, 0x10, 0x8c, 0x50, 0x83, 0xe8, 0x21, 0xde, 0xbc, 0xc5, 0x64, 0x88, 0x82,
	0xed, 0xc6, 0xdd, 0x6d, 0xdf, 0xd3, 0x37, 0x92, 0xec, 0x26, 0x92, 0x34, 0x3d, 0xed, 0x30, 0xff,
	0xcc, 0x37, 0xf3, 0xcf, 0x42, 0x58, 0x2a, 0x69, 0xe4, 0xa2, 0x90, 0xa2, 0x50, 0x65, 0x26, 0xb4,
	0xda, 0x8a, 0x6c, 0x25, 0x6c, 0x12, 0x47, 0xf6, 0xe1, 0xcf, 0x70, 0xb2, 0x54, 0x65, 0xb6, 0x24,
	0x13, 0xe7, 0x3a, 0xa1, 0x9f, 0x0d, 0x69, 0x83, 0x08, 0xc3, 0xd7, 0xcd, 0x4a, 0x07, 0x6c, 0xc6,
	0xe6, 0x7e, 0x62, 0x63, 0xe4, 0x70, 0xf8, 0x98, 0x9a, 0x34, 0xa2, 0xb5, 0x21, 0x15, 0xe7, 0x81,
	0x67, 0xb5, 0x4e, 0x8e, 0x5f, 0x02, 0xb6, 0x61, 0xba, 0x94, 0x6b, 0x4d, 0x78, 0x04, 0x5e, 0x9c,
	0x07, 0x6c, 0xe6, 0xcf, 0xfd, 0xc4, 0x8b, 0x73, 0x7e, 0x03, 0xd3, 0xff, 0xaa, 0x66, 0xe2, 0x2e,
	0x9d, 0xed, 0xa1, 0x5f, 0xb4, 0x56, 0xed, 0xc1, 0x59, 0x0d, 0x3f, 0x75, 0x45, 0x4f, 0x94, 0x7e,
	0x9b, 0xcf, 0x9a, 0xce, 0x6f, 0xdd, 0x5e, 0x4d, 0xb2, 0x6e, 0x45, 0x18, 0x46, 0x32, 0xa7, 0xc6,
	0x65, 0x15, 0xe3, 0x14, 0xfc, 0x17, 0x5d, 0x58, 0x73, 0x93, 0xa4, 0x0a, 0xaf, 0x7e, 0x19, 0x1c,
	0x57, 0xcd, 0x91, 0x54, 0xf4, 0x46, 0x6a, 0xfb, 0x95, 0x11, 0xde, 0xc1, 0xc8, 0x6e, 0x81, 0x67,
	0xee, 0x98, 0x62, 0xd7, 0x4f, 0x18, 0xf4, 0x05, 0x37, 0x95, 0x0f, 0xf0, 0x1e, 0xc6, 0xee, 0x42,
	0xd8, 0xab, 0x6a, 0x7e, 0x20, 0x3c, 0xdf, 0xa3, 0xb4, 0x01, 0xce, 0x4a, 0x07, 0xd0, 0xb1, 0xdc,
	0x01, 0x74, 0x7d, 0xf3, 0xc1, 0xc3, 0xe4, 0xfd, 0x40, 0x2c, 0xac, 0xfe, 0x31, 0xb6, 0xcf, 0xf5,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x0d, 0x20, 0x97, 0x2b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GrpcCoreServiceClient is the client API for GrpcCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcCoreServiceClient interface {
	GetId(ctx context.Context, in *GrpcGetIdRequest, opts ...grpc.CallOption) (*GrpcGetIdResponse, error)
	GetIds(ctx context.Context, in *GrpcGetIdsRequest, opts ...grpc.CallOption) (*GrpcGetIdsResponse, error)
	Health(ctx context.Context, in *GrpcHealthRequest, opts ...grpc.CallOption) (*GrpcHealthResponse, error)
}

type grpcCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcCoreServiceClient(cc grpc.ClientConnInterface) GrpcCoreServiceClient {
	return &grpcCoreServiceClient{cc}
}

func (c *grpcCoreServiceClient) GetId(ctx context.Context, in *GrpcGetIdRequest, opts ...grpc.CallOption) (*GrpcGetIdResponse, error) {
	out := new(GrpcGetIdResponse)
	err := c.cc.Invoke(ctx, "/proto.GrpcCoreService/GetId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcCoreServiceClient) GetIds(ctx context.Context, in *GrpcGetIdsRequest, opts ...grpc.CallOption) (*GrpcGetIdsResponse, error) {
	out := new(GrpcGetIdsResponse)
	err := c.cc.Invoke(ctx, "/proto.GrpcCoreService/GetIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcCoreServiceClient) Health(ctx context.Context, in *GrpcHealthRequest, opts ...grpc.CallOption) (*GrpcHealthResponse, error) {
	out := new(GrpcHealthResponse)
	err := c.cc.Invoke(ctx, "/proto.GrpcCoreService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcCoreServiceServer is the server API for GrpcCoreService service.
type GrpcCoreServiceServer interface {
	GetId(context.Context, *GrpcGetIdRequest) (*GrpcGetIdResponse, error)
	GetIds(context.Context, *GrpcGetIdsRequest) (*GrpcGetIdsResponse, error)
	Health(context.Context, *GrpcHealthRequest) (*GrpcHealthResponse, error)
}

// UnimplementedGrpcCoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcCoreServiceServer struct {
}

func (*UnimplementedGrpcCoreServiceServer) GetId(ctx context.Context, req *GrpcGetIdRequest) (*GrpcGetIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetId not implemented")
}
func (*UnimplementedGrpcCoreServiceServer) GetIds(ctx context.Context, req *GrpcGetIdsRequest) (*GrpcGetIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIds not implemented")
}
func (*UnimplementedGrpcCoreServiceServer) Health(ctx context.Context, req *GrpcHealthRequest) (*GrpcHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}

func RegisterGrpcCoreServiceServer(s *grpc.Server, srv GrpcCoreServiceServer) {
	s.RegisterService(&_GrpcCoreService_serviceDesc, srv)
}

func _GrpcCoreService_GetId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcGetIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcCoreServiceServer).GetId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GrpcCoreService/GetId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcCoreServiceServer).GetId(ctx, req.(*GrpcGetIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcCoreService_GetIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcGetIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcCoreServiceServer).GetIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GrpcCoreService/GetIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcCoreServiceServer).GetIds(ctx, req.(*GrpcGetIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcCoreService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcCoreServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GrpcCoreService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcCoreServiceServer).Health(ctx, req.(*GrpcHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcCoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GrpcCoreService",
	HandlerType: (*GrpcCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetId",
			Handler:    _GrpcCoreService_GetId_Handler,
		},
		{
			MethodName: "GetIds",
			Handler:    _GrpcCoreService_GetIds_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _GrpcCoreService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/go.grpc.srv.cm.proto",
}
